name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    defaults: 
      run:
        working-directory: diary-rs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install rustup
        run: curl https://sh.rustup.rs -sSf | sh
      - name: Cargo build
        run: cargo build
